modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/ITank/issues"

[[mods]]
modId="neotech"
displayName="Neo Tech"
version="1.0.0"
authors="Ewy"
credits="Test"
description="Test"

[[dependencies.neotech]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="AFTER"
side="BOTH"

[[dependencies.neotech]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21]"
ordering="NONE"
side="BOTH"